version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: taskify
      POSTGRES_PASSWORD: taskify
      POSTGRES_DB: taskify
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./apps/backend
    command: npm run start:dev
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://taskify:taskify@db:5432/taskify
    depends_on:
      - db
    volumes:
      - ./apps/backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./apps/frontend
    command: npm run dev
    restart: always
    ports:
      - '5173:5173'
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app

volumes:
  db_data:
